name: libthermo
channels:
  - conda-forge
dependencies:
  - cmake
  - make
  - ninja
  - vs2022-msvc-x64
  - vs2022-win-sdk-x64
  - gtest
  - xsimd
  - nanobind
  - python
  - nlohmann_json
  - boost-cpp
  - clang-format
