name: pythermo-dev
channels:
  - conda-forge
dependencies:
#  - cxx-compiler
  - vs2022-msvc-x64
  - vs2022-win-sdk-x64
  - cmake
  - ninja
  - gtest
  - gmock
  - pybind11
  - pytest
  - xtensor
  - xsimd
  - xtensor-python
  - numpy
  - tbb-devel
  - nlohmann_json
  - boost
